/**
 * Chinese strings for the vector-model section of the memory settings.
 *
 * Kept out of `zh.ts` because that file is generated by the extraction pass and is already close
 * to the repository's per-file line ceiling. These keys are hand-written, so they read as names
 * rather than hashes.
 */
export const zhEmbedding = {
  "memEmb.title": "向量模型",
  "memEmb.subtitle": "记忆的写入和检索都依赖它。语义检索比对的是向量，不是关键词。",

  "memEmb.roles.title": "两类模型，各管一段",
  "memEmb.roles.vector": "向量模型",
  "memEmb.roles.vectorDesc":
    "把文字转成固定长度的数值向量，是存取记忆的硬依赖。聊天模型无法替代——它返回的是文字，给不出向量。",
  "memEmb.roles.text": "整理模型",
  "memEmb.roles.textDesc":
    "普通聊天模型，只用于自动捕获和用户画像。不配置也不影响手动存取，只是不会自动帮你提炼记忆。",
  "memEmb.roles.current": "当前：{model}",
  "memEmb.roles.none": "未配置",
  "memEmb.roles.textHint": "在下方「记忆整理模型」中设置。",

  "memEmb.mode.title": "运行方式",
  "memEmb.mode.local": "本地运行",
  "memEmb.mode.localDesc": "在本机用 ONNX 推理，完全离线，不产生任何 API 费用。需要先下载模型文件。",
  "memEmb.mode.remote": "远程接口",
  "memEmb.mode.remoteDesc":
    "调用 OpenAI 兼容的 /embeddings 接口。不占磁盘和内存，但每次存取记忆都会发起一次 API 调用。",

  "memEmb.local.pick": "选择本地模型",
  "memEmb.local.dims": "{count} 维",
  "memEmb.local.context": "{count} 上下文",
  "memEmb.local.cost": "磁盘 {disk} · 内存峰值 {peak}",
  "memEmb.local.multilingual": "中英文均可",
  "memEmb.local.englishOnly": "偏英文",
  "memEmb.local.download": "下载",
  "memEmb.local.redownload": "重新下载",
  "memEmb.local.installed": "已下载",
  "memEmb.local.incomplete": "文件不全",
  "memEmb.local.delete": "删除本地文件",
  "memEmb.local.downloading": "正在下载 {received} / {total}",
  "memEmb.local.downloadFailed": "下载失败：{error}",
  "memEmb.local.selected": "使用中",
  "memEmb.local.notes.recommended": "推荐",
  "memEmb.local.notes.fastest": "最快",
  "memEmb.local.notes.quality-english": "英文质量优先",
  "memEmb.local.notes.long-context-english": "英文长文本",

  "memEmb.footprint.title": "占用说明",
  "memEmb.footprint.disk": "磁盘：选中的模型约 {size}，存放在 {path}",
  "memEmb.footprint.memory": "内存：载入后常驻约 {resident}，检索长文本时峰值约 {peak}",
  "memEmb.footprint.context":
    "内存主要由上下文长度决定，而非文件大小：8192 上下文的模型要为推理分配很大的工作区，所以文件更小的模型未必更省内存。以上数字为实测的进程内存增量。",
  "memEmb.footprint.quantized":
    "下载的是量化权重，体积和内存约为全精度版的四分之一。全精度版会让 ONNX 运行时在内存紧张的机器上直接分配失败，而检索质量的差异在记忆场景可以忽略。",
  "memEmb.footprint.mirror":
    "部分网络直连 huggingface.co 会超时，因此默认走 hf-mirror.com 镜像，失败才回退官方源。",
  "memEmb.footprint.cacheUsed": "当前缓存目录已占用 {size}。",

  "memEmb.remote.baseUrl": "接口地址",
  "memEmb.remote.baseUrlPlaceholder": "https://api.openai.com/v1",
  "memEmb.remote.baseUrlHint": "OpenAI 兼容的基础地址，插件会请求 {path}。",
  "memEmb.remote.model": "模型名称",
  "memEmb.remote.modelPlaceholder": "text-embedding-3-small",
  "memEmb.remote.key": "API Key",
  "memEmb.remote.keyPlaceholder": "sk-…",
  "memEmb.remote.keyStored": "已保存密钥，留空表示沿用。",
  "memEmb.remote.keyPrivacy": "密钥只写入本机配置文件，不会回传到界面。",
  "memEmb.remote.hint": "并非所有中转站都提供嵌入模型；若返回 model_not_found，说明该账号组没有配置嵌入模型。",

  "memEmb.save": "保存向量模型设置",
  "memEmb.saving": "保存中…",
  "memEmb.reload": "刷新",

  "embedding.saved": "已保存，OpenCode 重新载入后生效。",
  "embedding.saved.dimensionsChanged":
    "已保存。新模型的向量维度与原来不同，已存记忆需要重新嵌入后才能被检索到。",
  "embedding.download.started": "已开始下载，可以离开此页面，下载在后台继续。",
  "embedding.deleted": "已删除本地模型文件。",
  "embedding.error.baseUrlRequired": "请填写接口地址",
  "embedding.error.modelRequired": "请填写模型名称",
  "embedding.error.keyRequired": "请填写 API Key",
  "embedding.error.downloadBusy": "已有下载任务在进行中",
  "embedding.error.notInstalled": "该模型没有本地文件",
  "embedding.error.deleteFailed": "无法删除本地文件",
} as const;
