package com.aicoding.plugin.services

import com.intellij.openapi.project.Project
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import java.util.concurrent.TimeUnit

@Serializable
data class PermissionRule(
    val id: String,
    /** The permission kind: `bash`, `edit`, `websearch`… */
    val action: String,
    /** The pattern the rule matches. `*` means every operation of this kind. */
    val resource: String,
    val createdAt: Long = 0,
    /** True for `*`, which grants the whole category rather than one command. */
    val blanket: Boolean = false,
)

@Serializable
data class PermissionRuleList(
    val success: Boolean,
    val rules: List<PermissionRule> = emptyList(),
    val message: String? = null,
)

@Serializable
data class PermissionRuleDeleteRequest(
    /** Empty means every rule; otherwise only these ids are removed. */
    val ids: List<String> = emptyList(),
)

@Serializable
data class PermissionRuleActionResponse(
    val success: Boolean,
    val removed: Int = 0,
    val message: String? = null,
)

/**
 * Reads and revokes the standing approvals OpenCode stores when the user answers "always".
 *
 * These rules are invisible everywhere else and outrank the approval mode: `websearch` and `edit`
 * both declare `always: ["*"]`, so a single click permanently stops those categories from ever
 * asking again, in every session, across restarts. Without somewhere to see and undo that, the
 * only way back was editing a 700 MB SQLite file by hand.
 *
 * Access goes through `opencode db`, deliberately. The rows live in OpenCode's own database, which
 * the server holds open in WAL mode; its CLI already owns the correct connection, so this needs
 * neither a JDBC driver in the plugin nor IntelliJ's internal SQLite binding — the latter being an
 * unstable API we would have to re-verify on every platform version.
 */
class PermissionRuleService(private val project: Project) {

    private val json = Json { ignoreUnknownKeys = true }

    fun list(): PermissionRuleList = runCatching {
        val output = query(
            "SELECT id, action, resource, time_created FROM permission ORDER BY time_created DESC LIMIT 500"
        )
        val rules = json.decodeFromString<List<RawRule>>(output.ifBlank { "[]" }).map { raw ->
            PermissionRule(
                id = raw.id,
                action = raw.action,
                resource = raw.resource,
                createdAt = raw.time_created,
                blanket = raw.resource.trim() == "*",
            )
        }
        PermissionRuleList(success = true, rules = rules)
    }.getOrElse { PermissionRuleList(false, message = it.message ?: "无法读取已授权规则") }

    fun delete(request: PermissionRuleDeleteRequest): PermissionRuleActionResponse = runCatching {
        val statement = if (request.ids.isEmpty()) {
            "DELETE FROM permission"
        } else {
            // Ids are generated by OpenCode and never contain quotes, but they arrive over HTTP and
            // are interpolated into SQL, so anything unexpected is rejected rather than escaped.
            val safe = request.ids.filter { it.isNotBlank() && it.all { char -> char.isLetterOrDigit() || char == '_' } }
            require(safe.size == request.ids.size) { "规则 ID 含有非法字符" }
            require(safe.isNotEmpty()) { "没有要删除的规则" }
            "DELETE FROM permission WHERE id IN (${safe.joinToString(",") { "'$it'" }})"
        }
        val before = countRules()
        query(statement)
        val removed = (before - countRules()).coerceAtLeast(0)
        PermissionRuleActionResponse(success = true, removed = removed)
    }.getOrElse { PermissionRuleActionResponse(false, message = it.message ?: "无法撤销规则") }

    private fun countRules(): Int = runCatching {
        json.decodeFromString<List<RawCount>>(query("SELECT COUNT(*) AS c FROM permission").ifBlank { "[]" })
            .firstOrNull()?.c ?: 0
    }.getOrDefault(0)

    private fun query(sql: String): String {
        val executable = OpenCodeServerManager(project.basePath).resolveExecutable()
        val process = ProcessBuilder(executable, "db", "--format", "json", sql)
            .directory(project.basePath?.let { java.io.File(it) })
            .redirectErrorStream(false)
            .start()
        val output = process.inputStream.bufferedReader().use { it.readText() }
        val errors = process.errorStream.bufferedReader().use { it.readText() }
        if (!process.waitFor(QUERY_TIMEOUT_SECONDS, TimeUnit.SECONDS)) {
            process.destroyForcibly()
            error("读取规则库超时")
        }
        if (process.exitValue() != 0) error(errors.trim().ifBlank { "opencode db 返回 ${process.exitValue()}" })
        // The CLI prints its banner and logs on stderr, so stdout is JSON or empty.
        return output.trim()
    }

    @Serializable
    private data class RawRule(
        val id: String,
        val action: String = "",
        val resource: String = "",
        val time_created: Long = 0,
    )

    @Serializable
    private data class RawCount(val c: Int = 0)

    private companion object {
        const val QUERY_TIMEOUT_SECONDS = 20L
    }
}
